FIXUP: libnvdimm: add dax_dev sync flag
If CONFIG_DEV_DAX=y, we see the following build error.

drivers/dax/device.c: In function 'devm_create_dev_dax':
drivers/dax/device.c:661:12: error: too few arguments to function 'alloc_dax'
  dax_dev = alloc_dax(dev_dax, NULL, NULL);

The backport was incomplete and did not carry the upstream change in
devm_create_dev_dax().

BUG=chromium:991662
TEST=Build with CONFIG_DEV_DAX=y

Change-Id: I8b72c2372adb115f7eb92a1891ea04f01d4ead66
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1746607
Reviewed-by: Daniel Verkamp <dverkamp@chromium.org>
Reviewed-by: Stephen Barber <smbarber@chromium.org>
(cherry picked from commit 5d87c0fe2c945ec6d8521345ace38a261a7de94f)
Signed-off-by: Vaibhav Rustagi <vaibhavrustagi@google.com>

BUG=b:143356772
TEST=Build with allyesconfig
SOURCE=CHROMEOS(5d87c0fe2c94)

Change-Id: I4298df2a4aa6707db1ca8fd2fb57c380498737f5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/lakitu-kernel/+/2016909
Reviewed-by: Roy Yang <royyang@google.com>
Commit-Queue: Vaibhav Rustagi <vaibhavrustagi@google.com>
Tested-by: Vaibhav Rustagi <vaibhavrustagi@google.com>