fs/select: avoid clang stack usage warning
The select() implementation is carefully tuned to put a sensible amount
of data on the stack for holding a copy of the user space fd_set,
but not too large to risk overflowing the kernel stack.

When building a 32-bit kernel with clang, we need a little more space
than with gcc, which often triggers a warning:

fs/select.c:619:5: error: stack frame size of 1048 bytes in function core_sys_select [-Werror,-Wframe-larger-than=]
int core_sys_select(int n, fd_set __user *inp, fd_set __user *outp,

I experimentally found that for 32-bit ARM, reducing the maximum
stack usage by 64 bytes keeps us reliably under the warning limit
again.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Andi Kleen <ak@linux.intel.com>
(am from https://lore.kernel.org/patchwork/patch/1048528/)
(also found at https://lkml.kernel.org/r/20190307090146.1874906-1-arnd@arndb.de)

BUG=chromium:819808, chromium:968198
TEST=no stack frame size warning in core_sys_select when building
  with clang for veyron

Change-Id: I100a5f61704ccb45bcd1cf72d43e786c8155e16c
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1636485
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from commit df512869bebe0da6cc1961e9647c74dcab948a76)
Signed-off-by: Vaibhav Rustagi <vaibhavrustagi@google.com>

BUG=b:143356772
TEST=cos_tryjob
SOURCE=UPSTREAM(ad312f95d41c),CHROMEOS(df512869bebe)

Change-Id: I6cae9af6e3e777550d03e6c6362d091d422cde13