mm: Export do_munmap
The 0-day build bot reports the following build error, seen if SDCARD_FS
is built as module.

ERROR: do_munmap undefined!

Fixes: 84a1b7d3d312 (Included sdcardfs source code for kernel 3.0)
Reported-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from commit b41dbcdd46d2924787183d95536c71dcd8243519)
Signed-off-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from commit 6db7cb817c3feace57ca382d081b6638c1bf7251)
Signed-off-by: Vaibhav Rustagi <vaibhavrustagi@google.com>

BUG=b:143356772
TEST=cos_tryjob
SOURCE=CHROMEOS(6db7cb817c3f)

Change-Id: Iebeb8ad2e6064b0024358d47349ae8f9aeef3b7f