Restrict ALT_SYSCALL code to 64 bit builds
0day reports that 32 bit builds (i386) fail.

>> init/init_task.c:65:69: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .thread_info = INIT_THREAD_INFO(init_task),
                                                                        ^
init/init_task.c:65:69: note: (near initialization for init_task.thread_info.sys_call_table)

Since we dont support 32-bit builds (the syscall API is different), limit
ALT_SYSCALL support to 64-bit builds. Do it using ARCH_HAS_ALT_SYSCALL to make
sure it does not pop up again.

BUG=chromium:899792
TEST=Build i386:allmodconfig

Change-Id: Ibf5323b15a00ca3a8d27e0f16e225e7e6e278869
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1305534
Reviewed-by: Matthias Kaehlcke <mka@chromium.org>
(cherry picked from commit 5a03528ae6754fee9f8f9fa7031dcf77a804c027)
Signed-off-by: Vaibhav Rustagi <vaibhavrustagi@google.com>

BUG=b:143356772
TEST=cos_tryjob
SOURCE=CHROMEOS(5a03528ae675)

Change-Id: Ia1891f5a160c378ed75aa9e230127168391a29e5